config/routes.rb
Rating::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  
  resources :users
  resources :credit_ratings
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

app/models/credit_rating.rb
class CreditRating < ActiveRecord::Base
  attr_accessible :fitch_lt, :fitch_st, :moodys_lt, :moodys_st, :name, :sp_lt, :sp_st
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/credit_ratings_controller.rb
#encoding: utf-8
class CreditRatingsController < InheritedResources::Base
  before_filter :authenticate_user!

  def show
    if request.xhr?
      @credit_rating = CreditRating.find(params[:id])
      render layout: false
    else
      show!
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < InheritedResources::Base
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
    index!
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def show
    @credit_ratings = CreditRating.all
    show!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_opts
    {class: [controller_name, action_name], data: {controller: controller_name.capitalize, action: action_name.capitalize}}
  end
end

app/helpers/credit_ratings_helper.rb
module CreditRatingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/credit_ratings/_form.html.haml
= form_for @credit_rating do |f|
  - if @credit_rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@credit_rating.errors.count, "error")} prohibited this credit_rating from being saved:"
      %ul
        - @credit_rating.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :moodys_lt
    = f.text_field :moodys_lt
  .field
    = f.label :moodys_st
    = f.text_field :moodys_st
  .field
    = f.label :sp_lt
    = f.text_field :sp_lt
  .field
    = f.label :sp_st
    = f.text_field :sp_st
  .field
    = f.label :fitch_lt
    = f.text_field :fitch_lt
  .field
    = f.label :fitch_st
    = f.text_field :fitch_st
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/credit_ratings/edit.html.haml
%h1 Editing credit_rating

= render 'form'

= link_to 'Show', @credit_rating
\|
= link_to 'Back', credit_ratings_path

app/views/credit_ratings/index.html.haml
%h1 Listing credit ratings
%table.table.table-condensed
  %tr
    %th{:rowspan => "2"} ID
    %th{:bgcolor => "#FBF0DB", :colspan => "2"} Moody's
    %th{:bgcolor => "#FBF0DB", :colspan => "2"} Standart and Poors
    %th{:bgcolor => "#FBF0DB", :colspan => "2"} Fitch
    %th{:bgcolor => "#FBF0DB", :rowspan => "2"} Name
    - if current_user.has_role? :admin
      %th{:bgcolor => "#FBF0DB", :rowspan => "2"} Actions
    
    %tr
      %td{:bgcolor => "#999"} Long Term
      %td{:bgcolor => "#999"} Short Term
      %td{:bgcolor => "#999"} Long Term
      %td{:bgcolor => "#999"} Short Term
      %td{:bgcolor => "#999"} Long Term
      %td{:bgcolor => "#999"} Short Term

  - @credit_ratings.each do |credit_rating|
    %tr
      %td= credit_rating.id
      %td= credit_rating.moodys_lt
      %td= credit_rating.moodys_st
      %td= credit_rating.sp_lt
      %td= credit_rating.sp_st
      %td= credit_rating.fitch_lt
      %td= credit_rating.fitch_st
      %td= credit_rating.name
      - if current_user.has_role? :admin
        %td
          = link_to 'Show', credit_rating
          |
          = link_to 'Edit', edit_credit_rating_path(credit_rating)
          |
          = link_to 'Destroy', credit_rating, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Credit rating', new_credit_rating_path

app/views/credit_ratings/new.html.haml
%h1 New credit_rating

= render 'form'

= link_to 'Back', credit_ratings_path

app/views/credit_ratings/show.html.haml
moodys_lt: #{@credit_rating.moodys_lt}, 
moodys_st: #{@credit_rating.moodys_st}, 
sp_lt: #{@credit_rating.sp_lt},
sp_st: #{@credit_rating.sp_st},
fitch_lt: #{@credit_rating.fitch_lt},
fitch_st: #{@credit_rating.fitch_st}

app/views/home/index.html.haml
%h3 Main rating page

%table.table.table-striped
  %tr
    %th ID
    %th Name
    %th Ratings set
   
  - @users.each do |user|
    %tr{data: {id: user.id}}
      %td= user.id
      %td= link_to user.name, user
      %td not yet rated

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Ratings", root_path, class: 'brand'
%ul.nav
  %li= link_to "Home", root_path
  %li= link_to "Users", users_path
  %li= link_to "Rating", credit_ratings_path

%ul.nav#auth
  - if user_signed_in?
    %li= link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li= link_to 'Admin', users_path
    %li= link_to 'Logout', destroy_user_session_path, :method => 'delete'
  - else
    %li= link_to 'Login', new_user_session_path
    %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Rating Application"
      %meta{:content => content_for?(:description) ? yield(:description) : "Test Rating Application", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{body_opts}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/users/_ratings_list.html.haml
.modal-header
  %a.close{"data-dismiss" => "modal"} ×
  %h3 Credits Ratings
.modal-body
  %table.table.table-condensed#ratings-list
    %thead
      %th{:bgcolor => "#FBF0DB", :rowspan => "2"} Name
      %th{:bgcolor => "#FBF0DB", :colspan => "2"} Moody's
      %th{:bgcolor => "#FBF0DB", :colspan => "2"} Standart and Poors
      %th{:bgcolor => "#FBF0DB", :colspan => "2"} Fitch
      %tr
        %th{:bgcolor => "#999"} Long Term
        %th{:bgcolor => "#999"} Short Term
        %th{:bgcolor => "#999"} Long Term
        %th{:bgcolor => "#999"} Short Term
        %th{:bgcolor => "#999"} Long Term
        %th{:bgcolor => "#999"} Short Term

    %tbody
      - @credit_ratings.each do |credit_rating|
        %tr
          %td.js-name{data: {id: credit_rating.id}}= credit_rating.name
          %td.js-moodys-lt= credit_rating.moodys_lt
          %td.js-moodys-st= credit_rating.moodys_st
          %td.js-sp-lt= credit_rating.sp_lt
          %td.js-sp-st= credit_rating.sp_st
          %td.js-fitch-lt= credit_rating.fitch_lt
          %td.js-fitch-st= credit_rating.fitch_st

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 #{@user.name} Ratings

.control-group
  .controls
    .input-append
      %p= text_field_tag "", "", class: "js-test-field", :style => "width: 550px;"
      %p= text_field_tag "", "", class: "js-quantity-field", :style => "width: 550px;"
      %br
      %br
      %br
      %br
      %p= text_field_tag "", "", class: "js-field", :style => "width: 550px;"